Fix missing cstdint on GCC 13
Without this change the code can not be compiled with the latest GCC 13
because an error reported on `openlocationcode.cc:139:3`.

```
error: 'int64_t' was not declared in this scope
note: 'int64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
```

The porting guide of GCC 13 explains,
that `cstdint` might need to be explicitly included:
https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes

Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>